
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftLESSleftEQUALSleftDOTCONSOLE DOT EQUALS ID IF LESS LOG LPAREN NUMBER RPAREN SEMI VARprogram : statementsstatements : statement\n                      | statements statement\n                      | statement : VAR ID EQUALS NUMBER SEMIstatement : IF LPAREN ID LESS NUMBER RPAREN statementstatement : CONSOLE DOT LOG LPAREN ID RPAREN SEMI'
    
_lr_action_items = {'VAR':([0,2,3,7,17,20,22,23,],[4,4,-2,-3,-5,4,-6,-7,]),'IF':([0,2,3,7,17,20,22,23,],[5,5,-2,-3,-5,5,-6,-7,]),'CONSOLE':([0,2,3,7,17,20,22,23,],[6,6,-2,-3,-5,6,-6,-7,]),'$end':([0,1,2,3,7,17,22,23,],[-4,0,-1,-2,-3,-5,-6,-7,]),'ID':([4,9,16,],[8,12,19,]),'LPAREN':([5,13,],[9,16,]),'DOT':([6,],[10,]),'EQUALS':([8,],[11,]),'LOG':([10,],[13,]),'NUMBER':([11,15,],[14,18,]),'LESS':([12,],[15,]),'SEMI':([14,21,],[17,23,]),'RPAREN':([18,19,],[20,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,20,],[3,7,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','js_parser.py',55),
  ('statements -> statement','statements',1,'p_statements','js_parser.py',59),
  ('statements -> statements statement','statements',2,'p_statements','js_parser.py',60),
  ('statements -> <empty>','statements',0,'p_statements','js_parser.py',61),
  ('statement -> VAR ID EQUALS NUMBER SEMI','statement',5,'p_statement_declaration','js_parser.py',65),
  ('statement -> IF LPAREN ID LESS NUMBER RPAREN statement','statement',7,'p_statement_if','js_parser.py',69),
  ('statement -> CONSOLE DOT LOG LPAREN ID RPAREN SEMI','statement',7,'p_statement_print','js_parser.py',73),
]
